In [7]:
#Numpy arrays

#two lists named height and weight are initialized
height=[2.80,2.84,2.91,2.89,2.84]    
weight=[80.24,89.96,90.65,86.40,87.98]

#import 'numpy' as 'np'
import numpy as np
np_height=np.array(height)
np_weight=np.array(weight)

print(type(np_height))   # returns class 'numpy.ndarray'
print(type(np_weight))

#finding body mass index(BMI) for all the 5 values
bmi=np_weight/np_height**2
print(bmi)

#finding values greater than 10.50
# For a boolean response
bmi > 10.50

# Print only those observations above 10.50
bmi[bmi > 10.50]



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[10.23469388 11.15354096 10.70488067 10.34470373 10.90805396]


array([11.15354096, 10.70488067, 10.90805396])

In [8]:
#Weight convertor
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

# Create a numpy array np_weight_kg from weight_kg
np_weight_kg=np.array(weight_kg) 

# Create np_weight_lbs from np_weight_kg
np_weight_lbs=np_weight_kg/2.2

# Print out np_weight_lbs
print(np_weight_lbs)

[37.11363636 44.32727273 43.29545455 42.26363636 39.17272727 40.20454545]


In [9]:
#Pandas
dict={"country":["India","China","Germany","Belgium"],
     "capital":["New Delhi","Beijing","Berlin","Brussels"],
      "area": [8.516, 17.10, 3.286, 9.597],
      "population": [200.4, 143.5, 1252, 1357] }
#importing 'pandas' as 'pd'
import pandas as pd
pd_dict=pd.DataFrame(dict)
print(pd_dict)


   country    capital    area  population
0    India  New Delhi   8.516       200.4
1    China    Beijing  17.100       143.5
2  Germany     Berlin   3.286      1252.0
3  Belgium   Brussels   9.597      1357.0


In [10]:
#changing index values
pd_dict.index=["IN","CH","GER","BE"]
print(pd_dict)

     country    capital    area  population
IN     India  New Delhi   8.516       200.4
CH     China    Beijing  17.100       143.5
GER  Germany     Berlin   3.286      1252.0
BE   Belgium   Brussels   9.597      1357.0


In [16]:
#reading csv file
import pandas as pd
data=pd.read_csv("accidentlatlong_threeyear.csv",header=0)
data

id        lat       long
0      2017_3170101413326007731  52.956923  10.603024
1      2017_3170101310112038751  52.379596   9.809079
2      2017_3170101310112038391  52.377291  10.038980
3      2017_3170101310112032251  52.399306   9.880214
4      2017_3170101213326033171  52.185437  10.086394
...                         ...        ...        ...
54329               2018_139338  52.276801   8.043732
54330               2018_139341  52.286450   8.042752
54331               2018_139342  53.231162   7.467708
54332               2018_139344  52.625553  10.084627
54333               2018_139347  52.839934   8.160514

[54334 rows x 3 columns]

In [20]:
#different ways of printing the data

# Print out id column as Pandas Series
print(data['id'])          #or data['id']

# Print out id column as Pandas DataFrame
print(data[['id']])      #or data[['id']]

# Print out DataFrame with  columns
print(data[['id', 'lat','long']])      #or data[['id', 'lat','long']]   

0        2017_3170101413326007731
1        2017_3170101310112038751
2        2017_3170101310112038391
3        2017_3170101310112032251
4        2017_3170101213326033171
                   ...           
54329                 2018_139338
54330                 2018_139341
54331                 2018_139342
54332                 2018_139344
54333                 2018_139347
Name: id, Length: 54334, dtype: object
                             id
0      2017_3170101413326007731
1      2017_3170101310112038751
2      2017_3170101310112038391
3      2017_3170101310112032251
4      2017_3170101213326033171
...                         ...
54329               2018_139338
54330               2018_139341
54331               2018_139342
54332               2018_139344
54333               2018_139347

[54334 rows x 1 columns]
                             id        lat       long
0      2017_3170101413326007731  52.956923  10.603024
1      2017_3170101310112038751  52.379596   9.809079
2      2017_317

In [29]:
#accessing rows
data[4:7]       # 4 included and 7 excluded

#searching specific value in the rows
data.loc[data['id']=='2018_13934']
data.loc[['id','lat']]


KeyError: "None of [Index(['id', 'lat'], dtype='object')] are in the [index]"